version: "3"

services:
  backend:
    build: ./src
    ports:
      - 8001:8000
    env_file:
      - config/db/.env
    depends_on:
      - db
    entrypoint:
      - "/code/entrypoint.sh"

  db:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "test_db_user"
        ]
      timeout: 90s
      interval: 10s
      retries: 3
    env_file:
      - config/db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: null
