"""add password to users

Revision ID: a95a6a030491
Revises: 07b1e1723b12
Create Date: 2022-02-07 13:05:39.231458

"""
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision = 'a95a6a030491'
down_revision = '07b1e1723b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
